// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int count1 = 0;
		int count2 = 0;
		for(int i = 0; i < n; i++){
			double num = Math.random();
			if(num > 0.5){
				count1++ ;
			}else{
				count2++;
			}
		}
		System.out.println("> 0.5: " + count1 + " times");
		System.out.println("<= 0.5: " + count2 + " times");
		if(count2 != 0 ){
			System.out.println("Ratio: " + (double)count1/ count2 );
		}
	}
}
